### ISSUE TITLE
Add Conventional Commit to ormus repository

### ISSUE THREAD

**Issue by gohossein** [ormushq/ormus#7]
We want to use [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0-beta.2/) to structure our commit message and also automate code versioning & changelog.
We follow the [Angular commit message guidelines](https://github.com/angular/angular/blob/22b96b9/CONTRIBUTING.md#commit-message-format).

These are some resources that might be helpful:
- https://github.com/go-semantic-release/semantic-release
- https://mokkapps.de/blog/how-to-automatically-generate-a-helpful-changelog-from-your-git-commit-messages
- https://www.philipp-doblhofer.at/en/blog/automatic-changelog-and-versioning-with-git/#:~:text=Commit%20Convention,also%20configure%20your%20own%20conventions.
- https://docs.github.com/en/repositories/releasing-projects-on-github/automatically-generated-release-notes
- https://github.com/marketplace/actions/auto-generate-changelog
- https://github.com/cookpete/auto-changelog
- https://blog.logrocket.com/automatically-generate-and-release-a-changelog-with-node-js/
- https://blog.jobins.jp/generate-changelog-from-git-commit-messages

It would be great to do it without third-party tools and just using GitHub actions. But if it's not possible, the second preference is to use a tool written in Golang so this does not force us to use npm packages (installing node-related artifacts in our ci/cd infra would be a pain).

**Comment by AtaReversei** [comment]
I'm not really sure but as far as I know we could enforce a tight standard on branch names, commit messages, project validity (it could be built in every commit that we check out) and many other things using github actions. I think we could use `post-receive` for these kind of things to make sure project is valid at any given commit (but i'm not sure, I'm not an expert).
And to make developers' lives easier we could use libraries like [lefthook](https://github.com/evilmartians/lefthook) or [husky for go](https://github.com/automation-co/husky) which is inspired from husky.js and using these tools we can implement [commitlint rules](https://commitlint.js.org/#/reference-rules) or any other custom rules. This way any developer can check if their commit is valid and won't be rejected when pushed to a remote repository.

**Comment by gohossein** [comment]
Thanks, Ata jan, [husky for go](https://github.com/automation-co/husky) is a good option. We don't need to force this rule in every commit, we can just add it to the pull request cicd pipeline, in this way, everyone who creates a new pull request should set a valid pull commit message.

**Comment by gohossein** [comment]
Also we'll try to keep git history linear (rebase strategy) so for every pull-request developers should squash their commit to single final commit and rebase the branch with `main` branch. In this way only the final pull-request commit should follow commit message guidelines.

**Comment by DOO-DEV** [comment]
https://github.com/ormushq/ormus/issues/7#issuecomment-1789466932

As far I discover we can define github workflows and track things like pull request at given state like(closed, sync...) here is a demo :
```yaml
name: validate pull request commit message

on:
  pull_request:
    types:
      - synchronize
      - closed

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Check commit squash commit message
        run: |
          # Fetch the pull request and checkout the merge commit
          PR_NUMBER=${{ github.event.pull_request.number }}
          git fetch origin pull/${{ PR_NUMBER }}/merge:pr-${{ PR_NUMBER }}
          git checkout pr-${{ PR_NUMBER }}
          
          # Define your commit message pattern (e.g., start with "test:")
          # This is where we can define our commit guidelines and check for them.
          PATTERN="^test:"
          
          # Get the squashed commit message
          COMMIT_MESSAGE=$(git log --format=%B -n 1 HEAD)
          
          if ! [[ "$COMMIT_MESSAGE" =~ $PATTERN ]]; then
            echo "Invalid squashed commit message: $COMMIT_MESSAGE"
            exit 1
          fi
        continue-on-error: true

      - name: Set Status Check
        if: failure()
        run: echo "Invalid squashed commit message" && exit 1
```

**Comment by gocastsian** [comment]
> [#7 (comment)](https://github.com/ormushq/ormus/issues/7#issuecomment-1789466932)
> 
> As far I discover we can define github workflows and track things like pull request at given state like(closed, sync...) here is a demo :
> 
> ```yaml
> name: validate pull request commit message
> 
> on:
>   pull_request:
>     types:
>       - synchronize
>       - closed
> 
> jobs:
>   validate:
>     runs-on: ubuntu-latest
> 
>     steps:
>       - name: Check commit squash commit message
>         run: |
>           # Fetch the pull request and checkout the merge commit
>           PR_NUMBER=${{ github.event.pull_request.number }}
>           git fetch origin pull/${{ PR_NUMBER }}/merge:pr-${{ PR_NUMBER }}
>           git checkout pr-${{ PR_NUMBER }}
>           
>           # Define your commit message pattern (e.g., start with "test:")
>           # This is where we can define our commit guidelines and check for them.
>           PATTERN="^test:"
>           
>           # Get the squashed commit message
>           COMMIT_MESSAGE=$(git log --format=%B -n 1 HEAD)
>           
>           if ! [[ "$COMMIT_MESSAGE" =~ $PATTERN ]]; then
>             echo "Invalid squashed commit message: $COMMIT_MESSAGE"
>             exit 1
>           fi
>         continue-on-error: true
> 
>       - name: Set Status Check
>         if: failure()
>         run: echo "Invalid squashed commit message" && exit 1
> ```
> 
> right now this workflow runs on 'closed' and 'synchronize' status of pull request. all we need is prevent merging when this script throw an error
> 
> the commit guidelines can add to the script(see the example that must begin with "test:")

Thanks @DOO-DEV jan, it would be great if you can complete this workflow on a test github repo and commit the code as a pull request for ormus.

**Comment by DOO-DEV** [comment]
One solution I found and work on my test repository:

:bookmark_tabs: First add workflow file under ```.github/workflows``` directory

```yml

name: PR Lint

on:
  pull_request:
    types: [opened, edited, reopened, synchronize, ready_for_review]
    branches: [main]

  workflow_dispatch:

jobs:
  pr-lint:
    name: Validate PR commit title meets commit convention
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v4.5.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          validateSingleCommit: true
          validateSingleCommitMatchesPrTitle: true
```

:bookmark_tabs: Configure the repository settings like this: 
1.  Turn off "Allow rebase merging"  and "Allow merge commits"<br/>
![image](https://github.com/ormushq/ormus/assets/96613482/d22cdbc9-9057-4755-a427-11347d99dc62)

2.  Under Branch protection rules add this rule:<br/>
![image](https://github.com/ormushq/ormus/assets/96613482/384cfaad-570f-4f77-adb2-24fab4f2bdc1)

And finally this is the result of the workflow run:<br/>
![image](https://github.com/ormushq/ormus/assets/96613482/98429ec1-63a6-4a8b-914d-573c5842a514)

This is my test repository make pull request to test the behavior of this workflow:
:link: https://github.com/DOO-DEV/learning-git-workflows

:bell: If this is ok give a signal to create a pull request @gohossein
